name: Publish Release
on:
  push:
    branches: [ master ]
    tags:
    - v*.*
jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install libgcrypt
      run: sudo apt-get install -y libgcrypt-dev
    - name: Build
      run: make
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          make_latest: true
          tag_name: "v2.3"
          files: |
            radiusplugin.so
            radiusplugin.cnf
